services:
  vms-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.php82

  intra-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.php82

  pilot-app:
    image: eproc-vms-vms-app:latest
